# Generated by Django 5.2.1 on 2025-07-14 21:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classes', '0002_initial'),
        ('e_learning', '0002_initial'),
        ('students', '0001_initial'),
        ('subjects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subjects.subject'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='e_learning.course'),
        ),
        migrations.AddField(
            model_name='aipredictedscore',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='e_learning.course'),
        ),
        migrations.AddField(
            model_name='courseannouncement',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='announcements', to='e_learning.course'),
        ),
        migrations.AddField(
            model_name='courseannouncement',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='coursechapter',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='e_learning.course'),
        ),
        migrations.AddField(
            model_name='coursecohortlink',
            name='class_level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classes.classlevel'),
        ),
        migrations.AddField(
            model_name='coursecohortlink',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='e_learning.course'),
        ),
        migrations.AddField(
            model_name='coursecohortlink',
            name='stream',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='classes.stream'),
        ),
        migrations.AddField(
            model_name='courseenrollment',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='e_learning.course'),
        ),
        migrations.AddField(
            model_name='courseenrollment',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elearning_enrollments', to='students.student'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='chapter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='e_learning.coursechapter'),
        ),
        migrations.AddField(
            model_name='liveclasssession',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='live_sessions', to='e_learning.course'),
        ),
        migrations.AddField(
            model_name='liveclasssession',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='message',
            name='sender',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='messagethread',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='e_learning.course'),
        ),
        migrations.AddField(
            model_name='messagethread',
            name='participants',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='message',
            name='thread',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='e_learning.messagethread'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quizzes', to='e_learning.course'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='quizquestion',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='e_learning.quiz'),
        ),
        migrations.AddField(
            model_name='quizsubmission',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='e_learning.quiz'),
        ),
        migrations.AddField(
            model_name='quizsubmission',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.student'),
        ),
        migrations.AddField(
            model_name='studentlessonprogress',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='e_learning.lesson'),
        ),
        migrations.AddField(
            model_name='studentlessonprogress',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.student'),
        ),
        migrations.AddField(
            model_name='teacheractivitylog',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='e_learning.course'),
        ),
        migrations.AddField(
            model_name='teacheractivitylog',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='assignmentsubmission',
            unique_together={('assignment', 'student')},
        ),
        migrations.AlterUniqueTogether(
            name='course',
            unique_together={('institution', 'subject', 'title')},
        ),
        migrations.AlterUniqueTogether(
            name='coursechapter',
            unique_together={('course', 'order')},
        ),
        migrations.AlterUniqueTogether(
            name='coursecohortlink',
            unique_together={('course', 'class_level', 'stream')},
        ),
        migrations.AlterUniqueTogether(
            name='courseenrollment',
            unique_together={('student', 'course')},
        ),
        migrations.AlterUniqueTogether(
            name='quizsubmission',
            unique_together={('quiz', 'student')},
        ),
        migrations.AlterUniqueTogether(
            name='studentlessonprogress',
            unique_together={('student', 'lesson')},
        ),
    ]
