# Generated by Django 5.2.1 on 2025-11-26 11:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('e_library', '0001_initial'),
        ('subjects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='elibraryresource',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='e_library_resources', to='subjects.subject'),
        ),
        migrations.AddField(
            model_name='elibraryresource',
            name='uploader',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_resources', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='aiassistededit',
            name='resource',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_logs', to='e_library.elibraryresource'),
        ),
        migrations.AddField(
            model_name='elibraryresource',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='resources', to='e_library.elibrarytag'),
        ),
        migrations.AddField(
            model_name='resourcerating',
            name='resource',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='e_library.elibraryresource'),
        ),
        migrations.AddField(
            model_name='resourcerating',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='resourceversion',
            name='resource',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='e_library.elibraryresource'),
        ),
        migrations.AddField(
            model_name='resourceviewlog',
            name='resource',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='e_library.elibraryresource'),
        ),
        migrations.AddField(
            model_name='resourceviewlog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='elibraryresource',
            index=models.Index(fields=['institution'], name='e_library_e_institu_f2de79_idx'),
        ),
        migrations.AddIndex(
            model_name='elibraryresource',
            index=models.Index(fields=['resource_type'], name='e_library_e_resourc_fab9cb_idx'),
        ),
        migrations.AddIndex(
            model_name='elibraryresource',
            index=models.Index(fields=['visibility'], name='e_library_e_visibil_cfbf75_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='resourcerating',
            unique_together={('resource', 'user')},
        ),
    ]
