# Generated by Django 5.2.1 on 2025-07-17 14:35

import django.db.models.deletion
import django.utils.timezone
import students.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('guardians', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(max_length=50)),
                ('year', models.IntegerField()),
                ('average_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('behavior_rating', models.PositiveIntegerField(blank=True, null=True)),
                ('comments', models.TextField(blank=True, null=True)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='MedicalFlag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condition', models.CharField(max_length=255)),
                ('notes', models.TextField(blank=True, null=True)),
                ('critical', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=100, null=True)),
                ('admission_number', models.CharField(max_length=50, unique=True)),
                ('national_id', models.CharField(blank=True, max_length=50, null=True)),
                ('birth_certificate_number', models.CharField(blank=True, max_length=50, null=True)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10)),
                ('photo', models.ImageField(blank=True, null=True, upload_to=students.models.student_photo_path)),
                ('enrollment_status', models.CharField(choices=[('active', 'Active'), ('suspended', 'Suspended'), ('graduated', 'Graduated'), ('transferred', 'Transferred'), ('inactive', 'Inactive'), ('expelled', 'Expelled')], default='active', max_length=20)),
                ('date_joined', models.DateField(default=django.utils.timezone.now)),
                ('date_left', models.DateField(blank=True, null=True)),
                ('religion', models.CharField(blank=True, max_length=50, null=True)),
                ('disability', models.CharField(blank=True, max_length=100, null=True)),
                ('health_notes', models.TextField(blank=True, null=True)),
                ('wallet_balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('is_boarding', models.BooleanField(default=False)),
                ('parent_access_code', models.CharField(blank=True, help_text='Unique code for guardian mobile login', max_length=50, null=True)),
                ('ai_insights', models.TextField(blank=True, help_text='Full AI-generated performance summary', null=True)),
                ('performance_comments', models.TextField(blank=True, help_text='Readable comments from AI', null=True)),
                ('recommended_books', models.JSONField(blank=True, help_text='AI-suggested books', null=True)),
                ('recommended_teachers', models.JSONField(blank=True, help_text='AI-suggested teachers or mentors', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['class_level', 'stream', 'last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='StudentDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('document', models.FileField(upload_to='students/documents/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='StudentExitRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('active', 'Active'), ('suspended', 'Suspended'), ('graduated', 'Graduated'), ('transferred', 'Transferred'), ('inactive', 'Inactive'), ('expelled', 'Expelled')], max_length=100)),
                ('exit_date', models.DateField()),
                ('notes', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='StudentHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change_type', models.CharField(max_length=50)),
                ('date_changed', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-date_changed'],
            },
        ),
        migrations.CreateModel(
            name='GuardianRelationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relationship', models.CharField(max_length=50)),
                ('is_primary', models.BooleanField(default=False)),
                ('guardian', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='linked_students', to='guardians.guardian')),
            ],
        ),
    ]
