# Generated by Django 5.2.1 on 2026-01-06 11:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_initial'),
        ('classes', '0004_alter_classlevel_unique_together_and_more'),
        ('students', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentStreamEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], max_length=20)),
                ('enrolled_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.academicyear')),
                ('stream', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_enrollments', to='classes.stream')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stream_enrollments', to='students.student')),
            ],
        ),
    ]
