# Generated by Django 5.2.1 on 2025-11-29 09:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('alumni', '0001_initial'),
        ('institutions', '0001_initial'),
        ('students', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='alumnimentorship',
            name='mentee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alumni_mentees', to='students.student'),
        ),
        migrations.AddField(
            model_name='alumninotification',
            name='institution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institutions.institution'),
        ),
        migrations.AddField(
            model_name='alumninotification',
            name='sent_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='alumniprofile',
            name='institution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institutions.institution'),
        ),
        migrations.AddField(
            model_name='alumniprofile',
            name='student',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='alumni_profile', to='students.student'),
        ),
        migrations.AddField(
            model_name='alumninotification',
            name='recipient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='alumni.alumniprofile'),
        ),
        migrations.AddField(
            model_name='alumnimentorship',
            name='mentor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentorships', to='alumni.alumniprofile'),
        ),
        migrations.AddField(
            model_name='alumnimembership',
            name='alumni',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='alumni.alumniprofile'),
        ),
        migrations.AddField(
            model_name='alumnijobopportunity',
            name='posted_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posted_jobs', to='alumni.alumniprofile'),
        ),
        migrations.AddField(
            model_name='alumnifeedback',
            name='alumni',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alumni.alumniprofile'),
        ),
        migrations.AddField(
            model_name='alumnieventregistration',
            name='alumni',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alumni.alumniprofile'),
        ),
        migrations.AddField(
            model_name='alumniemployment',
            name='alumni',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employment_records', to='alumni.alumniprofile'),
        ),
        migrations.AddField(
            model_name='alumnidonation',
            name='alumni',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alumni.alumniprofile'),
        ),
        migrations.AddField(
            model_name='alumniachievement',
            name='alumni',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to='alumni.alumniprofile'),
        ),
        migrations.AddField(
            model_name='alumnitestimonial',
            name='alumni',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='testimonials', to='alumni.alumniprofile'),
        ),
        migrations.AddField(
            model_name='alumnitestimonial',
            name='institution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institutions.institution'),
        ),
        migrations.AddField(
            model_name='alumnivolunteer',
            name='alumni',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alumni.alumniprofile'),
        ),
        migrations.AddField(
            model_name='alumnivolunteer',
            name='institution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institutions.institution'),
        ),
        migrations.AlterUniqueTogether(
            name='alumnimentorship',
            unique_together={('mentor', 'mentee')},
        ),
        migrations.AlterUniqueTogether(
            name='alumnieventregistration',
            unique_together={('event', 'alumni')},
        ),
    ]
