# Generated by Django 5.2.1 on 2025-11-29 09:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('institutions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('app_label', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_default', models.BooleanField(default=True)),
                ('linked_group', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth.group')),
            ],
        ),
        migrations.CreateModel(
            name='SchoolModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allowed_modules', to='institutions.institution')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modules.systemmodule')),
            ],
            options={
                'unique_together': {('institution', 'module')},
            },
        ),
        migrations.CreateModel(
            name='ModulePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('codename', models.CharField(max_length=150)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_permissions', to='modules.systemmodule')),
            ],
            options={
                'unique_together': {('module', 'codename')},
            },
        ),
    ]
