# Generated by Django 5.2.1 on 2025-11-29 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolmodule',
            name='custom',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='systemmodule',
            name='default_package',
            field=models.CharField(choices=[('basic', 'Basic'), ('pro', 'Pro'), ('enterprise', 'Enterprise')], default='basic', max_length=20),
        ),
    ]
