# Generated by Django 5.2.1 on 2025-12-01 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0002_schoolmodule_custom_systemmodule_default_package'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='systemmodule',
            name='default_package',
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_custom', models.BooleanField(default=False)),
                ('modules', models.ManyToManyField(blank=True, related_name='plans', to='modules.systemmodule')),
            ],
        ),
    ]
