# Generated by Django 5.2.1 on 2025-07-17 14:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classes', '0001_initial'),
        ('institutions', '0001_initial'),
        ('teachers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='stream',
            name='class_teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='streams_as_class_teacher', to='teachers.teacher'),
        ),
        migrations.AddField(
            model_name='stream',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='streams_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='stream',
            name='institution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='streams', to='institutions.institution'),
        ),
        migrations.AddField(
            model_name='stream',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='streams_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='classlevel',
            unique_together={('institution', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='stream',
            unique_together={('class_level', 'name', 'academic_year', 'institution')},
        ),
    ]
