# Generated by Django 5.2.1 on 2026-01-02 22:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0002_initial'),
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stream',
            name='class_teacher',
        ),
        migrations.AddField(
            model_name='classlevel',
            name='class_teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='classes_as_class_teacher', to='teachers.teacher'),
        ),
        migrations.AddField(
            model_name='stream',
            name='stream_teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='streams_as_stream_teacher', to='teachers.teacher'),
        ),
        migrations.AlterField(
            model_name='classlevel',
            name='default_promotion_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='previous_levels', to='classes.classlevel'),
        ),
    ]
