# Generated by Django 5.2.1 on 2026-01-06 11:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_initial'),
        ('classes', '0003_remove_stream_class_teacher_classlevel_class_teacher_and_more'),
        ('institutions', '0004_institution_status'),
        ('students', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='classlevel',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='stream',
            unique_together={('class_level', 'academic_year', 'code')},
        ),
        migrations.AlterField(
            model_name='classlevel',
            name='code',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='stream',
            name='code',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='classlevel',
            unique_together={('institution', 'code')},
        ),
        migrations.RemoveField(
            model_name='stream',
            name='average_attendance_rate',
        ),
        migrations.RemoveField(
            model_name='stream',
            name='average_score',
        ),
        migrations.RemoveField(
            model_name='stream',
            name='institution',
        ),
        migrations.RemoveField(
            model_name='stream',
            name='last_ai_evaluation',
        ),
        migrations.RemoveField(
            model_name='stream',
            name='rank_within_class_level',
        ),
        migrations.CreateModel(
            name='ClassLevelAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_students', models.PositiveIntegerField()),
                ('average_score', models.DecimalField(decimal_places=2, max_digits=6)),
                ('calculated_at', models.DateTimeField(auto_now_add=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.academicyear')),
                ('class_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to='classes.classlevel')),
                ('top_stream', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='classes.stream')),
            ],
            options={
                'verbose_name': 'Class Level Analytics',
                'verbose_name_plural': 'Class Level Analytics',
                'ordering': ['-calculated_at'],
                'unique_together': {('class_level', 'academic_year')},
            },
        ),
        migrations.CreateModel(
            name='StreamAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_students', models.PositiveIntegerField()),
                ('average_score', models.DecimalField(decimal_places=2, max_digits=6)),
                ('attendance_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('discipline_index', models.DecimalField(decimal_places=2, max_digits=5)),
                ('calculated_at', models.DateTimeField(auto_now_add=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.academicyear')),
                ('stream', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to='classes.stream')),
            ],
            options={
                'verbose_name': 'Stream Analytics',
                'verbose_name_plural': 'Stream Analytics',
                'ordering': ['-calculated_at'],
                'unique_together': {('stream', 'academic_year')},
            },
        ),
        migrations.CreateModel(
            name='StudentStreamEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Active'), ('transferred', 'Transferred'), ('completed', 'Completed'), ('withdrawn', 'Withdrawn')], default='active', max_length=20)),
                ('date_assigned', models.DateField(auto_now_add=True)),
                ('date_left', models.DateField(blank=True, null=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_enrollments_classes', to='academics.academicyear')),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stream_assignments_classes', to=settings.AUTH_USER_MODEL)),
                ('stream', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments_classes', to='classes.stream')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stream_enrollments_classes', to='students.student')),
            ],
            options={
                'verbose_name': 'Student Stream Enrollment',
                'verbose_name_plural': 'Student Stream Enrollments',
                'indexes': [models.Index(fields=['student', 'academic_year'], name='classes_stu_student_2183d7_idx'), models.Index(fields=['stream', 'status'], name='classes_stu_stream__722ff4_idx')],
                'unique_together': {('student', 'academic_year')},
            },
        ),
    ]
