# Generated by Django 5.2.1 on 2025-07-17 14:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('co_curricular', '0001_initial'),
        ('institutions', '0001_initial'),
        ('students', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='activityattendance',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.student'),
        ),
        migrations.AddField(
            model_name='activitycategory',
            name='institution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institutions.institution'),
        ),
        migrations.AddField(
            model_name='activity',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='co_curricular.activitycategory'),
        ),
        migrations.AddField(
            model_name='activityevent',
            name='activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='co_curricular.activity'),
        ),
        migrations.AddField(
            model_name='activityevent',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='activityevent',
            name='institution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institutions.institution'),
        ),
        migrations.AddField(
            model_name='activitysession',
            name='activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='co_curricular.activity'),
        ),
        migrations.AddField(
            model_name='activitysession',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='activityattendance',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='co_curricular.activitysession'),
        ),
        migrations.AddField(
            model_name='coachassignmenthistory',
            name='activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='co_curricular.activity'),
        ),
        migrations.AddField(
            model_name='coachassignmenthistory',
            name='coach',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='coachfeedback',
            name='coach',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='studentactivityparticipation',
            name='activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='co_curricular.activity'),
        ),
        migrations.AddField(
            model_name='studentactivityparticipation',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.student'),
        ),
        migrations.AddField(
            model_name='coachfeedback',
            name='participation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='co_curricular.studentactivityparticipation'),
        ),
        migrations.AddField(
            model_name='activityperformance',
            name='participation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='co_curricular.studentactivityparticipation'),
        ),
        migrations.AddField(
            model_name='studentaward',
            name='activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='co_curricular.activity'),
        ),
        migrations.AddField(
            model_name='studentaward',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.student'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='preferred_categories',
            field=models.ManyToManyField(blank=True, to='co_curricular.activitycategory'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='student',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='students.student'),
        ),
        migrations.AddField(
            model_name='studentreflection',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='studentreflection',
            name='participation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='co_curricular.studentactivityparticipation'),
        ),
        migrations.AddField(
            model_name='talentrecommendation',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.student'),
        ),
        migrations.AddField(
            model_name='talentrecommendation',
            name='suggested_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='activityattendance',
            unique_together={('session', 'student')},
        ),
        migrations.AlterUniqueTogether(
            name='studentactivityparticipation',
            unique_together={('student', 'activity')},
        ),
    ]
