# Generated by Django 5.2.1 on 2025-07-14 21:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('institutions', '0001_initial'),
        ('medical', '0001_initial'),
        ('students', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='healthalert',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_alerts', to='students.student'),
        ),
        migrations.AddField(
            model_name='medicalflag',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.student'),
        ),
        migrations.AddField(
            model_name='medicalvisit',
            name='attended_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='handled_visits', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='medicalvisit',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_visits', to='students.student'),
        ),
        migrations.AddField(
            model_name='dispensedmedicine',
            name='visit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicines_dispensed', to='medical.medicalvisit'),
        ),
        migrations.AddField(
            model_name='medicineinventory',
            name='institution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicines', to='institutions.institution'),
        ),
        migrations.AddField(
            model_name='dispensedmedicine',
            name='medicine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medical.medicineinventory'),
        ),
        migrations.AddField(
            model_name='sickbayvisit',
            name='institution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institutions.institution'),
        ),
        migrations.AddField(
            model_name='sickbayvisit',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.student'),
        ),
        migrations.AlterUniqueTogether(
            name='medicineinventory',
            unique_together={('institution', 'name')},
        ),
    ]
