# Generated by Django 5.2.1 on 2025-11-26 11:55

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0002_initial'),
        ('institutions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdmissionDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('birth_cert', 'Birth Certificate'), ('kcpe_result', 'KCPE Result Slip'), ('id_card', 'ID Card'), ('doctor_report', 'Doctor Report'), ('orphan_cert', 'Orphan Certificate'), ('passport_photo', 'Passport Photo'), ('other', 'Other')], max_length=50)),
                ('file', models.FileField(upload_to='admissions/documents/')),
                ('uploaded_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='AdmissionOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offer_letter', models.FileField(upload_to='admissions/offers/')),
                ('issued_on', models.DateField()),
                ('expiry_date', models.DateField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('expired', 'Expired')], default='pending', max_length=20)),
                ('acceptance_date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AdmissionWorkflowStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_name', models.CharField(max_length=100)),
                ('completed', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('remarks', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('other_names', models.CharField(blank=True, max_length=100)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(max_length=20)),
                ('nationality', models.CharField(max_length=100)),
                ('county', models.CharField(max_length=100)),
                ('sub_county', models.CharField(blank=True, max_length=100)),
                ('previous_school', models.CharField(blank=True, max_length=255)),
                ('previous_class', models.CharField(blank=True, max_length=100)),
                ('application_source', models.CharField(choices=[('website', 'Website'), ('referral', 'Referral'), ('walk_in', 'Walk-in'), ('agent', 'Agent'), ('social_media', 'Social Media'), ('other', 'Other')], default='other', max_length=30)),
                ('application_status', models.CharField(choices=[('pending', 'Pending'), ('shortlisted', 'Shortlisted'), ('under_review', 'Under Review'), ('interviewed', 'Interviewed'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('enrolled', 'Enrolled'), ('withdrawn', 'Withdrawn')], default='pending', max_length=20)),
                ('is_converted_to_student', models.BooleanField(default=False)),
                ('parent_name', models.CharField(max_length=255)),
                ('parent_phone', models.CharField(max_length=20)),
                ('parent_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('guardian_name', models.CharField(blank=True, max_length=255)),
                ('guardian_phone', models.CharField(blank=True, max_length=20)),
                ('guardian_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('orphan_status', models.CharField(choices=[('none', 'Not Orphaned'), ('partial', 'Partial Orphan'), ('full', 'Full Orphan')], default='none', max_length=10)),
                ('orphan_proof', models.FileField(blank=True, null=True, upload_to='admissions/orphan_proofs/')),
                ('has_disability', models.BooleanField(default=False)),
                ('disability_details', models.TextField(blank=True)),
                ('has_chronic_illness', models.BooleanField(default=False)),
                ('illness_details', models.TextField(blank=True)),
                ('doctor_report', models.FileField(blank=True, null=True, upload_to='admissions/doctor_reports/')),
                ('career_dream', models.CharField(blank=True, max_length=255)),
                ('talents', models.TextField(blank=True)),
                ('allergies', models.TextField(blank=True)),
                ('passport_photo', models.ImageField(blank=True, null=True, upload_to='admissions/photos/')),
                ('submitted_on', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='EntranceExam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_date', models.DateField()),
                ('score', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('remarks', models.TextField(blank=True)),
                ('passed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='AdmissionAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=50)),
                ('model_name', models.CharField(max_length=100)),
                ('record_id', models.PositiveIntegerField()),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('notes', models.TextField(blank=True)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AdmissionComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AdmissionSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('intake_date', models.DateField()),
                ('application_deadline', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.academicyear')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institutions.institution')),
            ],
        ),
    ]
