# Generated by Django 5.2.1 on 2025-07-14 21:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admissions', '0001_initial'),
        ('classes', '0001_initial'),
        ('institutions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='admissionsession',
            name='level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classes.classlevel'),
        ),
        migrations.AddField(
            model_name='admissionworkflowstep',
            name='completed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='applicant',
            name='admission_session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admissions.admissionsession'),
        ),
        migrations.AddField(
            model_name='applicant',
            name='entry_class_level',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='classes.classlevel'),
        ),
        migrations.AddField(
            model_name='applicant',
            name='institution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institutions.institution'),
        ),
        migrations.AddField(
            model_name='admissionworkflowstep',
            name='applicant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflow_steps', to='admissions.applicant'),
        ),
        migrations.AddField(
            model_name='admissionoffer',
            name='applicant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admissions.applicant'),
        ),
        migrations.AddField(
            model_name='admissiondocument',
            name='applicant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='admissions.applicant'),
        ),
        migrations.AddField(
            model_name='admissioncomment',
            name='applicant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='admissions.applicant'),
        ),
        migrations.AddField(
            model_name='entranceexam',
            name='applicant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admissions.applicant'),
        ),
        migrations.AlterUniqueTogether(
            name='applicant',
            unique_together={('institution', 'email', 'admission_session')},
        ),
    ]
