# Generated by Django 5.2.1 on 2025-07-17 14:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('discipline', '0001_initial'),
        ('institutions', '0001_initial'),
        ('students', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='disciplinecase',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.student'),
        ),
        migrations.AddField(
            model_name='disciplinecase',
            name='witnesses',
            field=models.ManyToManyField(blank=True, related_name='witnessed_discipline_cases', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='disciplinaryaction',
            name='discipline_case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='discipline.disciplinecase'),
        ),
        migrations.AddField(
            model_name='disciplinecategory',
            name='institution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institutions.institution'),
        ),
        migrations.AddField(
            model_name='disciplinecase',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='discipline.disciplinecategory'),
        ),
    ]
