# Generated by Django 5.2.1 on 2025-06-08 10:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exams', '0001_initial'),
        ('institutions', '0001_initial'),
        ('students', '0001_initial'),
        ('subjects', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='examresult',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.student'),
        ),
        migrations.AddField(
            model_name='examsubject',
            name='exam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='exams.exam'),
        ),
        migrations.AddField(
            model_name='examsubject',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subjects.subject'),
        ),
        migrations.AddField(
            model_name='gradeboundary',
            name='institution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institutions.institution'),
        ),
        migrations.AddField(
            model_name='gradeboundary',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subjects.subject'),
        ),
        migrations.AddField(
            model_name='studentscore',
            name='exam_subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='exams.examsubject'),
        ),
        migrations.AddField(
            model_name='studentscore',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.student'),
        ),
        migrations.AlterUniqueTogether(
            name='exam',
            unique_together={('name', 'class_level', 'stream', 'term', 'year')},
        ),
        migrations.AlterUniqueTogether(
            name='examresult',
            unique_together={('exam', 'student')},
        ),
        migrations.AlterUniqueTogether(
            name='examsubject',
            unique_together={('exam', 'subject')},
        ),
        migrations.AlterUniqueTogether(
            name='gradeboundary',
            unique_together={('institution', 'subject', 'grade')},
        ),
        migrations.AlterUniqueTogether(
            name='studentscore',
            unique_together={('exam_subject', 'student')},
        ),
    ]
