# Generated by Django 5.2.1 on 2025-07-17 14:35

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classes', '0001_initial'),
        ('institutions', '0001_initial'),
        ('payroll', '0001_initial'),
        ('subjects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('staff_id', models.CharField(max_length=50, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=100, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='teachers/photos/')),
                ('bio', models.TextField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('marital_status', models.CharField(blank=True, max_length=50, null=True)),
                ('national_id', models.CharField(blank=True, max_length=50, null=True)),
                ('employment_type', models.CharField(choices=[('full_time', 'Full-Time'), ('part_time', 'Part-Time'), ('contract', 'Contract'), ('volunteer', 'Volunteer')], default='full_time', max_length=20)),
                ('job_title', models.CharField(blank=True, max_length=100, null=True)),
                ('department', models.CharField(blank=True, max_length=100, null=True)),
                ('designation', models.CharField(choices=[('academic', 'Academic'), ('non_academic', 'Non-Academic')], default='academic', max_length=20)),
                ('joining_date', models.DateField()),
                ('leaving_date', models.DateField(blank=True, null=True)),
                ('assigned_roles', models.JSONField(blank=True, help_text='e.g., Head of Department, Exam Coordinator', null=True)),
                ('qualifications', models.TextField(blank=True, null=True)),
                ('professional_certifications', models.TextField(blank=True, null=True)),
                ('specializations', models.TextField(blank=True, null=True)),
                ('education_history', models.JSONField(blank=True, null=True)),
                ('languages_spoken', models.CharField(blank=True, max_length=255, null=True)),
                ('work_experience', models.JSONField(blank=True, null=True)),
                ('transfer_records', models.JSONField(blank=True, null=True)),
                ('teaching_history', models.JSONField(blank=True, null=True)),
                ('digital_portfolio_url', models.URLField(blank=True, null=True)),
                ('teaching_philosophy', models.TextField(blank=True, null=True)),
                ('performance_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('ai_insights', models.TextField(blank=True, null=True)),
                ('recommended_subjects', models.JSONField(blank=True, null=True)),
                ('student_feedback_summary', models.TextField(blank=True, null=True)),
                ('teacher_ratings', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('disciplinary_flags', models.TextField(blank=True, null=True)),
                ('co_curricular_roles', models.CharField(blank=True, max_length=255, null=True)),
                ('dormitory_duties', models.CharField(blank=True, max_length=255, null=True)),
                ('substitution_availability', models.BooleanField(default=True)),
                ('available_for_virtual_teaching', models.BooleanField(default=False)),
                ('verified_virtual_tutor', models.BooleanField(default=False)),
                ('assigned_virtual_courses', models.JSONField(blank=True, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('alternative_contact', models.CharField(blank=True, max_length=20, null=True)),
                ('emergency_contact_name', models.CharField(blank=True, max_length=100, null=True)),
                ('emergency_contact_number', models.CharField(blank=True, max_length=20, null=True)),
                ('residence_address', models.TextField(blank=True, null=True)),
                ('postal_address', models.TextField(blank=True, null=True)),
                ('next_of_kin', models.CharField(blank=True, max_length=100, null=True)),
                ('next_of_kin_relationship', models.CharField(blank=True, max_length=50, null=True)),
                ('salary_scale', models.CharField(blank=True, max_length=50, null=True)),
                ('grade', models.CharField(blank=True, max_length=50, null=True)),
                ('payroll_profile', models.CharField(blank=True, max_length=100, null=True)),
                ('contract_renewal_due', models.DateField(blank=True, null=True)),
                ('promotion_due', models.DateField(blank=True, null=True)),
                ('leave_balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('daily_checkin_logs', models.JSONField(blank=True, null=True)),
                ('teacher_absenteeism_records', models.JSONField(blank=True, null=True)),
                ('leave_history', models.JSONField(blank=True, null=True)),
                ('approved_leave_days', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('timetable_pdf', models.FileField(blank=True, null=True, upload_to='teachers/timetables/')),
                ('bank_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='payroll.bankaccount')),
                ('class_levels_handled', models.ManyToManyField(blank=True, related_name='teachers', to='classes.classlevel')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teachers', to='institutions.institution')),
                ('streams_handled', models.ManyToManyField(blank=True, related_name='teachers', to='classes.stream')),
                ('subjects_taught', models.ManyToManyField(blank=True, related_name='teachers', to='subjects.subject')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teacher_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['last_name', 'first_name'],
                'unique_together': {('institution', 'staff_id')},
            },
        ),
    ]
