# Generated by Django 5.2.1 on 2025-06-08 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='timetable_pdf',
            field=models.FileField(blank=True, null=True, upload_to='teachers/timetables/'),
        ),
    ]
