# Generated by Django 5.2.1 on 2025-06-24 21:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0001_initial'),
        ('syllabus', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curriculumsubject',
            name='term',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.term'),
        ),
    ]
