# Generated by Django 5.2.1 on 2025-07-17 14:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('guardians', '0001_initial'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='guardianstudentlink',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guardian_links', to='students.student'),
        ),
        migrations.AlterUniqueTogether(
            name='guardian',
            unique_together={('user', 'institution')},
        ),
        migrations.AlterUniqueTogether(
            name='guardianstudentlink',
            unique_together={('guardian', 'student')},
        ),
    ]
