# Generated by Django 5.2.1 on 2025-06-22 15:17

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classes', '0001_initial'),
        ('exams', '0002_initial'),
        ('institutions', '0001_initial'),
        ('students', '0001_initial'),
        ('subjects', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneratedReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('academics', 'Academics'), ('finance', 'Finance'), ('attendance', 'Attendance'), ('discipline', 'Discipline'), ('medical', 'Medical'), ('overview', 'Institution Overview'), ('custom', 'Custom Report')], max_length=20)),
                ('access_level', models.CharField(choices=[('admin', 'Admin Only'), ('teacher', 'Teachers'), ('guardian', 'Guardians'), ('student', 'Students')], default='admin', max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('date_generated', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_auto_generated', models.BooleanField(default=False)),
                ('term', models.CharField(blank=True, max_length=50, null=True)),
                ('year', models.CharField(blank=True, max_length=4, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='reports/')),
                ('json_data', models.JSONField(blank=True, null=True)),
                ('class_level', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='classes.classlevel')),
                ('generated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institutions.institution')),
                ('stream', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='classes.stream')),
            ],
        ),
        migrations.CreateModel(
            name='ReportStudentPerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_marks', models.FloatField()),
                ('mean_score', models.FloatField()),
                ('grade', models.CharField(max_length=10)),
                ('rank', models.PositiveIntegerField()),
                ('position_out_of', models.PositiveIntegerField()),
                ('class_level', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='classes.classlevel')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_performances', to='reports.generatedreport')),
                ('stream', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='classes.stream')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.student')),
            ],
        ),
        migrations.CreateModel(
            name='ReportSubjectBreakdown',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('average_score', models.FloatField()),
                ('top_score', models.FloatField()),
                ('lowest_score', models.FloatField()),
                ('pass_rate', models.FloatField(help_text='Percentage of students who passed (0-100)')),
                ('failure_rate', models.FloatField()),
                ('most_common_grade', models.CharField(blank=True, max_length=10, null=True)),
                ('class_level', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='classes.classlevel')),
                ('exam', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='exams.exam')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_breakdowns', to='reports.generatedreport')),
                ('stream', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='classes.stream')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subjects.subject')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='taught_subjects', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
