# Generated by Django 5.2.1 on 2025-07-17 14:35

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classes', '0001_initial'),
        ('institutions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportSubjectBreakdown',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('average_score', models.FloatField()),
                ('top_score', models.FloatField()),
                ('lowest_score', models.FloatField()),
                ('pass_rate', models.FloatField()),
                ('failure_rate', models.FloatField()),
                ('most_common_grade', models.CharField(blank=True, max_length=10, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('flagged', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='GeneratedReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('academics', 'Academics'), ('finance', 'Finance'), ('attendance', 'Attendance'), ('discipline', 'Discipline'), ('medical', 'Medical'), ('overview', 'Institution Overview'), ('custom', 'Custom Report')], max_length=20)),
                ('access_level', models.CharField(choices=[('admin', 'Admin Only'), ('teacher', 'Teachers'), ('guardian', 'Guardians'), ('student', 'Students')], default='admin', max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('finalized', 'Finalized'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('date_generated', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_auto_generated', models.BooleanField(default=False)),
                ('term', models.CharField(blank=True, max_length=20, null=True)),
                ('year', models.CharField(blank=True, max_length=4, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='reports/')),
                ('json_data', models.JSONField(blank=True, null=True)),
                ('ai_summary', models.TextField(blank=True, null=True)),
                ('smart_flags', models.JSONField(blank=True, null=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('class_level', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='classes.classlevel')),
                ('generated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_reports', to=settings.AUTH_USER_MODEL)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institutions.institution')),
                ('stream', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='classes.stream')),
            ],
            options={
                'ordering': ['-date_generated'],
            },
        ),
        migrations.CreateModel(
            name='ReportAuditTrail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('performed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_trails', to='reports.generatedreport')),
            ],
        ),
        migrations.CreateModel(
            name='ReportPrintRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('copies', models.PositiveIntegerField(default=1)),
                ('print_center_notes', models.TextField(blank=True, null=True)),
                ('printed_file', models.FileField(blank=True, null=True, upload_to='reports/print/')),
                ('is_printed', models.BooleanField(default=False)),
                ('printed_at', models.DateTimeField(blank=True, null=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='print_requests', to='reports.generatedreport')),
                ('requested_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-requested_at'],
            },
        ),
        migrations.CreateModel(
            name='ReportStudentPerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_marks', models.FloatField()),
                ('mean_score', models.FloatField()),
                ('grade', models.CharField(max_length=10)),
                ('rank', models.PositiveIntegerField()),
                ('position_out_of', models.PositiveIntegerField()),
                ('comment', models.TextField(blank=True, null=True)),
                ('remedial_suggestion', models.TextField(blank=True, null=True)),
                ('flagged', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('class_level', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='classes.classlevel')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_performances', to='reports.generatedreport')),
                ('stream', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='classes.stream')),
            ],
        ),
    ]
