# Generated by Django 5.2.1 on 2025-11-29 09:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classes', '0001_initial'),
        ('exams', '0001_initial'),
        ('reports', '0001_initial'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportstudentperformance',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.student'),
        ),
        migrations.AddField(
            model_name='reportsubjectbreakdown',
            name='class_level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='classes.classlevel'),
        ),
        migrations.AddField(
            model_name='reportsubjectbreakdown',
            name='exam',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='exams.exam'),
        ),
        migrations.AddField(
            model_name='reportsubjectbreakdown',
            name='report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_breakdowns', to='reports.generatedreport'),
        ),
        migrations.AddField(
            model_name='reportsubjectbreakdown',
            name='stream',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='classes.stream'),
        ),
    ]
