# Generated by Django 5.2.1 on 2025-07-14 21:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reports', '0002_initial'),
        ('subjects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='reportsubjectbreakdown',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subjects.subject'),
        ),
        migrations.AddField(
            model_name='reportsubjectbreakdown',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subject_breakdown_teacher', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='generatedreport',
            index=models.Index(fields=['institution', 'report_type', 'term', 'year'], name='reports_gen_institu_2e27b2_idx'),
        ),
        migrations.AddIndex(
            model_name='generatedreport',
            index=models.Index(fields=['class_level', 'stream', 'year', 'term'], name='reports_gen_class_l_4bc24b_idx'),
        ),
        migrations.AddConstraint(
            model_name='generatedreport',
            constraint=models.UniqueConstraint(fields=('institution', 'report_type', 'term', 'year', 'class_level', 'stream'), name='unique_report_version', violation_error_message='Report already exists for class and term.'),
        ),
    ]
