# Generated by Django 5.2.1 on 2025-07-17 14:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0002_initial'),
        ('e_wallet', '0001_initial'),
        ('institutions', '0001_initial'),
        ('students', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='microfee',
            name='students',
            field=models.ManyToManyField(related_name='micro_fees', to='students.student'),
        ),
        migrations.AddField(
            model_name='microfee',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_micro_fees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='microfeeassignment',
            name='assigned_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_micro_fees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='microfeeassignment',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='micro_fees_student', to='students.student'),
        ),
        migrations.AddField(
            model_name='microfeeassignment',
            name='term',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='micro_fees', to='academics.term'),
        ),
        migrations.AddField(
            model_name='microfeepayment',
            name='micro_fee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='e_wallet.microfee'),
        ),
        migrations.AddField(
            model_name='microfeepayment',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.student'),
        ),
        migrations.AddField(
            model_name='wallet',
            name='institution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institutions.institution'),
        ),
        migrations.AddField(
            model_name='wallet',
            name='student',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to='students.student'),
        ),
        migrations.AddField(
            model_name='walletauditlog',
            name='actor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='walletauditlog',
            name='wallet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='e_wallet.wallet'),
        ),
        migrations.AddField(
            model_name='walletpolicy',
            name='institution',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wallet_policy', to='institutions.institution'),
        ),
        migrations.AddField(
            model_name='walletreminder',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='wallettopuprequest',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wallet_topups', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='wallettopuprequest',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.student'),
        ),
        migrations.AddField(
            model_name='wallettransaction',
            name='initiated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='wallettransaction',
            name='wallet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='e_wallet.wallet'),
        ),
        migrations.AlterUniqueTogether(
            name='microfeeassignment',
            unique_together={('student', 'term', 'fee_type')},
        ),
        migrations.AlterUniqueTogether(
            name='microfeepayment',
            unique_together={('micro_fee', 'student')},
        ),
    ]
