# Generated by Django 5.2.1 on 2025-06-25 16:01

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('institutions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IDCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('student', 'Student'), ('teacher', 'Teacher'), ('staff', 'Staff'), ('admin', 'Administrator')], max_length=20)),
                ('object_id', models.PositiveIntegerField()),
                ('unique_id', models.CharField(max_length=100, unique=True)),
                ('full_name', models.CharField(max_length=255)),
                ('photo', models.ImageField(upload_to='id_cards/photos/')),
                ('qr_code_image', models.ImageField(blank=True, null=True, upload_to='id_cards/qr/')),
                ('barcode_image', models.ImageField(blank=True, null=True, upload_to='id_cards/barcodes/')),
                ('class_or_department', models.CharField(blank=True, max_length=100)),
                ('issued_on', models.DateField(default=django.utils.timezone.now)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('revoked', models.BooleanField(default=False)),
                ('reason_revoked', models.TextField(blank=True)),
                ('digital_only', models.BooleanField(default=False)),
                ('printed', models.BooleanField(default=False)),
                ('last_printed_on', models.DateTimeField(blank=True, null=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institutions.institution')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DigitalIDToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=128, unique=True)),
                ('valid_until', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('id_card', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='id_cards.idcard')),
            ],
        ),
        migrations.CreateModel(
            name='IDCardAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('created', 'Created'), ('printed', 'Printed'), ('revoked', 'Revoked'), ('reissued', 'Reissued'), ('auto-regenerated', 'Auto-Regenerated')], max_length=30)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('notes', models.TextField(blank=True)),
                ('id_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='id_cards.idcard')),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='IDCardReissueRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('approved', models.BooleanField(default=False)),
                ('approved_on', models.DateTimeField(blank=True, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('handled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='id_reissue_handler', to=settings.AUTH_USER_MODEL)),
                ('requester', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='IDCardTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('background_color', models.CharField(default='#FFFFFF', max_length=20)),
                ('text_color', models.CharField(default='#000000', max_length=20)),
                ('font', models.CharField(default='Arial', max_length=100)),
                ('include_qr_code', models.BooleanField(default=True)),
                ('include_barcode', models.BooleanField(default=False)),
                ('include_signature', models.BooleanField(default=False)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='id_cards/templates/logos/')),
                ('background_image', models.ImageField(blank=True, null=True, upload_to='id_cards/templates/backgrounds/')),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institutions.institution')),
            ],
        ),
        migrations.AddField(
            model_name='idcard',
            name='template',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='id_cards.idcardtemplate'),
        ),
    ]
