# Generated by Django 5.2.1 on 2025-06-04 20:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classes', '0001_initial'),
        ('institutions', '0001_initial'),
        ('subjects', '0002_initial'),
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Period',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('MON', 'Monday'), ('TUE', 'Tuesday'), ('WED', 'Wednesday'), ('THU', 'Thursday'), ('FRI', 'Friday')], max_length=3)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='periods', to='institutions.institution')),
            ],
            options={
                'ordering': ['day', 'start_time'],
                'unique_together': {('day', 'start_time', 'institution')},
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('capacity', models.PositiveIntegerField(blank=True, null=True)),
                ('is_lab', models.BooleanField(default=False)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='institutions.institution')),
            ],
        ),
        migrations.CreateModel(
            name='SubjectAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lessons_per_week', models.PositiveSmallIntegerField()),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_assignments', to='institutions.institution')),
                ('stream', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_assignments', to='classes.stream')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='subjects.subject')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='teachers.teacher')),
            ],
            options={
                'unique_together': {('teacher', 'subject', 'stream')},
            },
        ),
        migrations.CreateModel(
            name='TimetableEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetable_entries', to='institutions.institution')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='timetable.period')),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='timetable_entries', to='timetable.room')),
                ('stream', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetable_entries', to='classes.stream')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetable_entries', to='subjects.subject')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetable_entries', to='teachers.teacher')),
            ],
            options={
                'ordering': ['period__day', 'period__start_time'],
                'unique_together': {('period', 'stream')},
            },
        ),
    ]
