# Generated by Django 5.2.1 on 2025-06-08 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0001_initial'),
        ('institutions', '0001_initial'),
        ('subjects', '0002_initial'),
        ('teachers', '0002_teacher_timetable_pdf'),
        ('timetable', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='period',
            options={'ordering': ['day', 'start_time'], 'verbose_name': 'Period', 'verbose_name_plural': 'Periods'},
        ),
        migrations.AlterModelOptions(
            name='room',
            options={'verbose_name': 'Room', 'verbose_name_plural': 'Rooms'},
        ),
        migrations.AlterModelOptions(
            name='subjectassignment',
            options={'verbose_name': 'Subject Assignment', 'verbose_name_plural': 'Subject Assignments'},
        ),
        migrations.AlterModelOptions(
            name='timetableentry',
            options={'ordering': ['period__day', 'period__start_time'], 'verbose_name': 'Timetable Entry', 'verbose_name_plural': 'Timetable Entries'},
        ),
        migrations.AlterUniqueTogether(
            name='timetableentry',
            unique_together={('period', 'stream', 'institution')},
        ),
        migrations.AddField(
            model_name='timetableentry',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterUniqueTogether(
            name='room',
            unique_together={('name', 'institution')},
        ),
        migrations.AlterUniqueTogether(
            name='subjectassignment',
            unique_together={('teacher', 'subject', 'stream', 'institution')},
        ),
    ]
