# Generated by Django 5.2.1 on 2025-06-04 20:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('subjects', '0001_initial'),
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjectteacher',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_links', to='teachers.teacher'),
        ),
        migrations.AlterUniqueTogether(
            name='subject',
            unique_together={('name', 'institution')},
        ),
        migrations.AlterUniqueTogether(
            name='subjectclasslevel',
            unique_together={('subject', 'class_level')},
        ),
        migrations.AlterUniqueTogether(
            name='subjectteacher',
            unique_together={('teacher', 'subject')},
        ),
    ]
