# Generated by Django 5.2.1 on 2025-11-26 11:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classes', '0002_initial'),
        ('subjects', '0001_initial'),
        ('teachers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='subjectassignment',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teachers.teacher'),
        ),
        migrations.AddField(
            model_name='subject',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='subjects.subjectcategory'),
        ),
        migrations.AddField(
            model_name='subjectclasslevel',
            name='class_level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_links', to='classes.classlevel'),
        ),
        migrations.AddField(
            model_name='subjectclasslevel',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_levels', to='subjects.subject'),
        ),
        migrations.AddField(
            model_name='subjectgradingscheme',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grading_schemes', to='subjects.subject'),
        ),
        migrations.AddField(
            model_name='subjectprerequisite',
            name='prerequisite',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prerequisites', to='subjects.subject'),
        ),
        migrations.AddField(
            model_name='subjectprerequisite',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='main_subject', to='subjects.subject'),
        ),
        migrations.AddField(
            model_name='subjectresource',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='subjects.subject'),
        ),
        migrations.AddField(
            model_name='subjectresource',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='subjectteacher',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_links', to='subjects.subject'),
        ),
        migrations.AddField(
            model_name='subjectteacher',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_links', to='teachers.teacher'),
        ),
        migrations.AddField(
            model_name='subjectversion',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='subjectversion',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='subjects.subject'),
        ),
        migrations.AlterUniqueTogether(
            name='subjectassessmentweight',
            unique_together={('subject', 'term', 'component')},
        ),
        migrations.AlterUniqueTogether(
            name='subjectassignment',
            unique_together={('institution', 'subject', 'teacher', 'class_level', 'stream', 'term', 'academic_year')},
        ),
        migrations.AlterUniqueTogether(
            name='subject',
            unique_together={('name', 'institution')},
        ),
        migrations.AlterUniqueTogether(
            name='subjectclasslevel',
            unique_together={('subject', 'class_level')},
        ),
        migrations.AlterUniqueTogether(
            name='subjectgradingscheme',
            unique_together={('subject', 'grade')},
        ),
        migrations.AlterUniqueTogether(
            name='subjectprerequisite',
            unique_together={('subject', 'prerequisite')},
        ),
        migrations.AlterUniqueTogether(
            name='subjectteacher',
            unique_together={('teacher', 'subject')},
        ),
        migrations.AlterUniqueTogether(
            name='subjectversion',
            unique_together={('subject', 'version_number')},
        ),
    ]
