# Generated by Django 5.2.1 on 2025-06-24 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0003_term'),
        ('syllabus', '0002_alter_curriculumsubject_term'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Term',
        ),
    ]
