# Generated by Django 5.2.1 on 2025-11-26 11:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('institutions', '0001_initial'),
        ('procurement', '0001_initial'),
        ('store_inventory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='procurementrequest',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='procurement_requests', to='store_inventory.itemcategory'),
        ),
        migrations.AddField(
            model_name='procurementrequest',
            name='institution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='procurement_requests', to='institutions.institution'),
        ),
        migrations.AddField(
            model_name='procurementrequest',
            name='requested_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='procurement_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='procurementlog',
            name='related_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='procurement.procurementrequest'),
        ),
        migrations.AddField(
            model_name='procurementapproval',
            name='request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='procurement.procurementrequest'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='institution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_orders', to='institutions.institution'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='issued_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_purchase_orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_orders', to='procurement.procurementrequest'),
        ),
        migrations.AddField(
            model_name='goodsreceivednote',
            name='po',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='grn', to='procurement.purchaseorder'),
        ),
        migrations.AddField(
            model_name='quotation',
            name='request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotations', to='procurement.procurementrequest'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='quotation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_orders', to='procurement.quotation'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='institution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='procurement_suppliers', to='institutions.institution'),
        ),
        migrations.AddField(
            model_name='quotation',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotations', to='procurement.supplier'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_orders', to='procurement.supplier'),
        ),
        migrations.AddField(
            model_name='supplierinvoice',
            name='po',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='procurement.purchaseorder'),
        ),
        migrations.AddField(
            model_name='payment',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='procurement.supplierinvoice'),
        ),
        migrations.AddField(
            model_name='tender',
            name='institution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='procurement_tenders', to='institutions.institution'),
        ),
        migrations.AddField(
            model_name='tender',
            name='request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tenders', to='procurement.procurementrequest'),
        ),
        migrations.AddField(
            model_name='quotation',
            name='tender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotations', to='procurement.tender'),
        ),
    ]
