# Generated by Django 5.2.1 on 2025-11-26 11:55

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolRegistrationRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('school_name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('country', models.CharField(max_length=100)),
                ('county', models.CharField(max_length=100)),
                ('sub_county', models.CharField(blank=True, max_length=100, null=True)),
                ('ward', models.CharField(blank=True, max_length=100, null=True)),
                ('village', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('institution_type', models.CharField(choices=[('PRIMARY', 'Primary School'), ('SECONDARY', 'Secondary School'), ('UNIVERSITY', 'University'), ('TECHNICAL', 'Technical Institute'), ('VIRTUAL', 'Virtual School'), ('OTHER', 'Other')], default='OTHER', max_length=50)),
                ('school_type', models.CharField(choices=[('public', 'Public'), ('private', 'Private'), ('community', 'Community'), ('other', 'Other')], default='other', max_length=50)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('approved', models.BooleanField(default=False)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('admin_created', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'School Registration Request',
                'verbose_name_plural': 'School Registration Requests',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('registration_number', models.CharField(blank=True, max_length=100, null=True)),
                ('country', models.CharField(db_index=True, max_length=100)),
                ('county', models.CharField(db_index=True, max_length=100)),
                ('sub_county', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('ward', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('village', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='institution_logos/')),
                ('primary_color', models.CharField(default='#0047AB', max_length=20)),
                ('secondary_color', models.CharField(default='#FFFFFF', max_length=20)),
                ('theme_mode', models.CharField(choices=[('light', 'Light'), ('dark', 'Dark')], default='light', max_length=10)),
                ('school_type', models.CharField(choices=[('public', 'Public'), ('private', 'Private'), ('community', 'Community'), ('other', 'Other')], default='other', max_length=20)),
                ('institution_type', models.CharField(choices=[('PRIMARY', 'Primary School'), ('SECONDARY', 'Secondary School'), ('UNIVERSITY', 'University'), ('TECHNICAL', 'Technical Institute'), ('VIRTUAL', 'Virtual School'), ('OTHER', 'Other')], default='OTHER', max_length=20)),
                ('ownership', models.CharField(blank=True, max_length=255, null=True)),
                ('funding_source', models.CharField(blank=True, max_length=255, null=True)),
                ('established_year', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('extra_info', models.JSONField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Institution',
                'verbose_name_plural': 'Institutions',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['country'], name='institution_country_a37e56_idx'), models.Index(fields=['county'], name='institution_county_66ed48_idx'), models.Index(fields=['sub_county'], name='institution_sub_cou_c99667_idx'), models.Index(fields=['ward'], name='institution_ward_1919fb_idx'), models.Index(fields=['village'], name='institution_village_82b880_idx'), models.Index(fields=['code'], name='institution_code_6def32_idx')],
            },
        ),
        migrations.CreateModel(
            name='SchoolAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('account_name', models.CharField(max_length=255)),
                ('account_number', models.CharField(max_length=50)),
                ('bank_name', models.CharField(blank=True, max_length=255, null=True)),
                ('branch', models.CharField(blank=True, max_length=255, null=True)),
                ('payment_type', models.CharField(choices=[('bank', 'Bank Account'), ('mobile_money', 'Mobile Money')], max_length=20)),
                ('mpesa_till_number', models.CharField(blank=True, max_length=20, null=True)),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='institutions.institution')),
            ],
            options={
                'verbose_name': 'School Account',
                'verbose_name_plural': 'School Accounts',
                'ordering': ['institution', 'account_name'],
                'unique_together': {('institution', 'account_number')},
            },
        ),
    ]
