# Generated by Django 5.2.1 on 2025-12-01 16:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0002_plan_institution_admin_user_institution_plan'),
        ('modules', '0003_remove_systemmodule_default_package_plan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institution',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='institutions', to='modules.plan'),
        ),
        migrations.DeleteModel(
            name='Plan',
        ),
    ]
