# Generated by Django 5.2.1 on 2025-12-29 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0003_alter_institution_plan_delete_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Suspended', 'Suspended'), ('Pending', 'Pending')], db_index=True, default='Pending', max_length=20),
        ),
    ]
